In [3]:
import numpy as np

In [4]:
list_1= [1,2,3,4]

In [5]:
arr=np.array(list_1)##converting list into numpy

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [9]:
np.asarray(list_1)

array([1, 2, 3, 4])

In [16]:
arr1=np.array([[1,2,3],[4,7,8]])

In [17]:
arr1

array([[1, 2, 3],
       [4, 7, 8]])

In [13]:
arr.ndim

1

In [19]:
arr1.ndim#aray with 2 dimension

2

In [20]:
arr1

array([[1, 2, 3],
       [4, 7, 8]])

In [21]:
arr

array([1, 2, 3, 4])

In [23]:
mat=np.matrix(list_1)

In [26]:
np.asanyarray(list_1) ##here list is converted into n dim array

array([1, 2, 3, 4])

In [25]:
np.asanyarray(mat)##mat is allready a type of array

matrix([[1, 2, 3, 4]])

In [27]:
arr

array([1, 2, 3, 4])

In [41]:
a=arr ##swallow copy

In [29]:
a


array([1, 2, 3, 4])

In [30]:
arr

array([1, 2, 3, 4])

In [31]:
arr[0]=100

In [32]:
a

array([100,   2,   3,   4])

In [33]:
arr

array([100,   2,   3,   4])

In [35]:
b= np.copy(arr)  ##deep copy

In [36]:
b

array([100,   2,   3,   4])

In [38]:
b[0]=234

In [39]:
b

array([234,   2,   3,   4])

In [40]:
arr

array([100,   2,   3,   4])

In [46]:
np.fromfunction(lambda i,j: i==j, (3,3))##from fn generate dataset as per given condition

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [47]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [50]:
[list(i*i for  i in range (5))] ##comprehension

[[0, 1, 4, 9, 16]]

In [59]:
##numpy
iterable = (i*i for i in range(5))

In [60]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [63]:
np.fromstring("22 45 56", sep =" ")

array([22., 45., 56.])

In [64]:
arr


array([100,   2,   3,   4])

In [65]:
arr1

array([[1, 2, 3],
       [4, 7, 8]])

In [66]:
arr.ndim

1

In [67]:
arr1.ndim

2

In [68]:
arr.size

4

In [69]:
arr1.size

6

In [70]:
arr.shape

(4,)

In [71]:
arr1.shape

(2, 3)

In [72]:
arr.dtype

dtype('int32')

In [73]:
arr1.dtype

dtype('int32')

# Numpy_2

In [74]:
import numpy as np

In [75]:
list(range(5))

[0, 1, 2, 3, 4]

In [76]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
list(range(0.7,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [80]:
np.arange(0.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [81]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [86]:
np.linspace(1,5,15)

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [87]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [89]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [91]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [93]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [98]:
arr= np.ones((3,4))

In [99]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [100]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [101]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [104]:
arr1=np.eye(5) ##identity matrix

In [105]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [106]:
import pandas as pd

In [107]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [109]:
np.random.rand(4,5)

array([[0.46819471, 0.9508489 , 0.69547472, 0.587842  , 0.49548818],
       [0.08430004, 0.38793916, 0.53046697, 0.41975856, 0.92436328],
       [0.4161897 , 0.97795071, 0.64738336, 0.54858268, 0.38260771],
       [0.80327525, 0.06503441, 0.10289008, 0.95465846, 0.68983351]])

In [110]:
np.random.randn(3,4)  ##

array([[-0.33622867, -0.33548959, -0.83309129,  1.31075601],
       [-0.92102113, -0.99863219,  0.66223318,  0.94796918],
       [-0.68418035,  0.14763996,  0.50706614,  2.47747404]])

In [112]:
arr2=np.random.randint(1,5,(3,4))

In [113]:
arr2


array([[1, 3, 4, 1],
       [2, 2, 1, 2],
       [1, 4, 3, 2]])

In [114]:
arr2.size

12

In [115]:
arr2.shape


(3, 4)

In [116]:
arr2.reshape(4,3)

array([[1, 3, 4],
       [1, 2, 2],
       [1, 2, 1],
       [4, 3, 2]])

In [117]:
arr2.reshape(6,2)

array([[1, 3],
       [4, 1],
       [2, 2],
       [1, 2],
       [1, 4],
       [3, 2]])

In [118]:
arr2.reshape(12,1)

array([[1],
       [3],
       [4],
       [1],
       [2],
       [2],
       [1],
       [2],
       [1],
       [4],
       [3],
       [2]])

In [119]:
arr2.reshape(2,6)

array([[1, 3, 4, 1, 2, 2],
       [1, 2, 1, 4, 3, 2]])

In [120]:
arr2.reshape(2,2,3)

array([[[1, 3, 4],
        [1, 2, 2]],

       [[1, 2, 1],
        [4, 3, 2]]])

In [121]:
arr3= np.random.randint(1,10,(5,6))

In [122]:
arr3

array([[8, 3, 3, 9, 4, 4],
       [9, 7, 6, 6, 4, 5],
       [9, 5, 6, 5, 4, 8],
       [1, 6, 6, 4, 7, 7],
       [9, 9, 4, 5, 5, 6]])

In [125]:
arr3>8

array([[False, False, False,  True, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True, False, False, False, False]])

In [126]:
arr3[arr3>8]

array([9, 9, 9, 9, 9])

In [127]:
arr3

array([[8, 3, 3, 9, 4, 4],
       [9, 7, 6, 6, 4, 5],
       [9, 5, 6, 5, 4, 8],
       [1, 6, 6, 4, 7, 7],
       [9, 9, 4, 5, 5, 6]])

In [130]:
arr3[0]

array([8, 3, 3, 9, 4, 4])

In [131]:
arr3[0,[0,1]]

array([8, 3])

In [132]:
arr3[2:4,[2,3]]

array([[6, 5],
       [6, 4]])

In [137]:
arr1=np.random.randint(1,7,(3,3))
arr2=np.random.randint(1,9,(3,3))

In [138]:
arr1

array([[2, 3, 4],
       [2, 4, 5],
       [4, 3, 6]])

In [139]:
arr2

array([[1, 2, 5],
       [5, 6, 7],
       [5, 6, 7]])

In [140]:
arr1+arr2

array([[ 3,  5,  9],
       [ 7, 10, 12],
       [ 9,  9, 13]])

In [141]:
arr1-arr2

array([[ 1,  1, -1],
       [-3, -2, -2],
       [-1, -3, -1]])

In [143]:
arr1*arr2 ##its not a matrix mailtiplication

array([[ 2,  6, 20],
       [10, 24, 35],
       [20, 18, 42]])

In [145]:
arr1@arr2 ##matrix multiplication

array([[37, 46, 59],
       [47, 58, 73],
       [49, 62, 83]])

In [146]:
arr1/arr2

array([[2.        , 1.5       , 0.8       ],
       [0.4       , 0.66666667, 0.71428571],
       [0.8       , 0.5       , 0.85714286]])

In [147]:
arr1%arr2

array([[0, 1, 4],
       [2, 4, 5],
       [4, 3, 6]], dtype=int32)

In [148]:
arr1/0

C:\Users\risha\AppData\Local\Temp\ipykernel_10880\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [149]:
#numpy broadcasting

In [151]:
arr = np.zeros((3,4))

In [152]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [154]:
arr+5 ##broadcasting 5 to all elements of arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [162]:
a= np.array([1,2,3,4])

In [163]:
a

array([1, 2, 3, 4])

In [164]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [170]:
b= np.array([[3,4,5]])

In [171]:
b

array([[3, 4, 5]])

In [172]:
arr+b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [173]:
b.T

array([[3],
       [4],
       [5]])

In [176]:
arr1=arr+b.T

In [177]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [178]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [179]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [180]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

# Numpy_3

In [7]:
import numpy as np
arr_1=np.random.randint(1,10,(4,4)) ##array manipulation

In [6]:
arr_1.reshape(8,2)

array([[5, 8],
       [5, 6],
       [2, 2],
       [8, 1],
       [1, 2],
       [9, 1],
       [2, 7],
       [9, 7]])

In [8]:
arr_1.T

array([[8, 6, 5, 1],
       [7, 2, 2, 5],
       [3, 6, 1, 3],
       [8, 9, 5, 5]])

In [10]:
arr_1

array([[8, 7, 3, 8],
       [6, 2, 6, 9],
       [5, 2, 1, 5],
       [1, 5, 3, 5]])

In [12]:
arr_1.flatten()

array([8, 7, 3, 8, 6, 2, 6, 9, 5, 2, 1, 5, 1, 5, 3, 5])

In [13]:
arr_1

array([[8, 7, 3, 8],
       [6, 2, 6, 9],
       [5, 2, 1, 5],
       [1, 5, 3, 5]])

In [14]:
np.expand_dims(arr_1,axis=1)

array([[[8, 7, 3, 8]],

       [[6, 2, 6, 9]],

       [[5, 2, 1, 5]],

       [[1, 5, 3, 5]]])

In [15]:
arr_1.ndim

2

In [16]:
np.expand_dims(arr_1,axis=0)

array([[[8, 7, 3, 8],
        [6, 2, 6, 9],
        [5, 2, 1, 5],
        [1, 5, 3, 5]]])

In [17]:
data= np.array([[1],[2],[3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [21]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [22]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [23]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [24]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
## bimary operators

In [2]:
import numpy as np
arr1= np.random.randint(1,10,(3,4))

arr2= np.random.randint(1,10,(3,4))

In [3]:
arr2

array([[9, 6, 1, 5],
       [4, 7, 7, 3],
       [5, 3, 9, 5]])

In [4]:
arr1

array([[3, 5, 3, 2],
       [2, 6, 2, 6],
       [9, 9, 4, 9]])

In [6]:
arr1+arr2

array([[12, 11,  4,  7],
       [ 6, 13,  9,  9],
       [14, 12, 13, 14]])

In [7]:
arr1*arr2

array([[27, 30,  3, 10],
       [ 8, 42, 14, 18],
       [45, 27, 36, 45]])

In [8]:
arr1/arr2

array([[0.33333333, 0.83333333, 3.        , 0.4       ],
       [0.5       , 0.85714286, 0.28571429, 2.        ],
       [1.8       , 3.        , 0.44444444, 1.8       ]])

In [9]:
arr1-arr2

array([[-6, -1,  2, -3],
       [-2, -1, -5,  3],
       [ 4,  6, -5,  4]])

In [10]:
-arr1

array([[-3, -5, -3, -2],
       [-2, -6, -2, -6],
       [-9, -9, -4, -9]])

In [11]:
-arr2

array([[-9, -6, -1, -5],
       [-4, -7, -7, -3],
       [-5, -3, -9, -5]])

In [15]:
# numpy string function

In [21]:
arr_2

NameError: name 'arr_2' is not defined

In [22]:
l= np.random.randint(1,5,(3,3))

In [23]:
l

array([[4, 3, 1],
       [1, 1, 2],
       [3, 1, 1]])

In [24]:
arr3=np.array(["rishabh", "singh"])

In [25]:
arr3

array(['rishabh', 'singh'], dtype='<U7')

In [26]:
np.char.upper(arr3)

array(['RISHABH', 'SINGH'], dtype='<U7')

In [27]:
np.char.capitalize(arr3)

array(['Rishabh', 'Singh'], dtype='<U7')

In [28]:
np.char.title(arr3)

array(['Rishabh', 'Singh'], dtype='<U7')

In [29]:
#numpy - maths functioln

In [31]:
a

NameError: name 'arr' is not defined

In [32]:
arr1= np.random.randint(1,10,(3,4))

In [33]:
arr1

array([[7, 7, 1, 8],
       [1, 8, 1, 9],
       [6, 8, 4, 8]])

In [34]:
np.sin(arr1)

array([[ 0.6569866 ,  0.6569866 ,  0.84147098,  0.98935825],
       [ 0.84147098,  0.98935825,  0.84147098,  0.41211849],
       [-0.2794155 ,  0.98935825, -0.7568025 ,  0.98935825]])

In [35]:
np.cos(arr1)

array([[ 0.75390225,  0.75390225,  0.54030231, -0.14550003],
       [ 0.54030231, -0.14550003,  0.54030231, -0.91113026],
       [ 0.96017029, -0.14550003, -0.65364362, -0.14550003]])

In [36]:
np.tan(arr1)

array([[ 0.87144798,  0.87144798,  1.55740772, -6.79971146],
       [ 1.55740772, -6.79971146,  1.55740772, -0.45231566],
       [-0.29100619, -6.79971146,  1.15782128, -6.79971146]])

In [37]:
np.log(arr1)

array([[1.94591015, 1.94591015, 0.        , 2.07944154],
       [0.        , 2.07944154, 0.        , 2.19722458],
       [1.79175947, 2.07944154, 1.38629436, 2.07944154]])

In [38]:
np.exp(arr1)

array([[1.09663316e+03, 1.09663316e+03, 2.71828183e+00, 2.98095799e+03],
       [2.71828183e+00, 2.98095799e+03, 2.71828183e+00, 8.10308393e+03],
       [4.03428793e+02, 2.98095799e+03, 5.45981500e+01, 2.98095799e+03]])

In [40]:
np.power(arr1,2)

array([[49, 49,  1, 64],
       [ 1, 64,  1, 81],
       [36, 64, 16, 64]], dtype=int32)

In [41]:
np.mean(arr1)

5.666666666666667

In [42]:
np.median(arr1)

7.0

In [45]:
np.std(arr1)

2.953340857778225

In [46]:
np.var(arr1)

8.722222222222223

In [47]:
np.min(arr1)

1

In [49]:
np.max(arr1)

9

In [50]:
# numpy arthmetic ioperations

In [51]:
arr1

array([[7, 7, 1, 8],
       [1, 8, 1, 9],
       [6, 8, 4, 8]])

In [52]:
arr2

array([[9, 6, 1, 5],
       [4, 7, 7, 3],
       [5, 3, 9, 5]])

In [53]:
arr1-arr2

array([[-2,  1,  0,  3],
       [-3,  1, -6,  6],
       [ 1,  5, -5,  3]])

In [54]:
np.subtract(arr1,arr2)

array([[-2,  1,  0,  3],
       [-3,  1, -6,  6],
       [ 1,  5, -5,  3]])

In [55]:
np.multiply(arr1,arr2)

array([[63, 42,  1, 40],
       [ 4, 56,  7, 27],
       [30, 24, 36, 40]])

In [56]:
np.mod(arr1,arr2)

array([[7, 1, 0, 3],
       [1, 1, 1, 0],
       [1, 2, 4, 3]], dtype=int32)

In [57]:
np.power(arr1,arr2)

array([[40353607,   117649,        1,    32768],
       [       1,  2097152,        1,      729],
       [    7776,      512,   262144,    32768]], dtype=int32)

In [58]:
np.sqrt(arr1)

array([[2.64575131, 2.64575131, 1.        , 2.82842712],
       [1.        , 2.82842712, 1.        , 3.        ],
       [2.44948974, 2.82842712, 2.        , 2.82842712]])

In [59]:
np.mean(arr1)

5.666666666666667

In [61]:
arr1.mean()

5.666666666666667

In [62]:
np.std(arr2)

2.3213980461973533

In [63]:
np.median(arr1)

7.0

# numpy_4

In [66]:
## sort , searching counting fn

In [67]:
arr= np.array([4,5,6,2,3,7,1,0])

In [68]:
arr

array([4, 5, 6, 2, 3, 7, 1, 0])

In [69]:
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [70]:
np.searchsorted(arr,6)

8

In [75]:
arr1=np.array([0,567,34,56,89,0,0,98])

In [76]:
arr1

array([  0, 567,  34,  56,  89,   0,   0,  98])

In [77]:
np.count_nonzero(arr1)

5

In [78]:
np.where(arr1>0) #gives indixes

(array([1, 2, 3, 4, 7], dtype=int64),)

In [80]:
np.extract(arr1>2,arr1)

array([567,  34,  56,  89,  98])

In [81]:
#byte swapping


In [82]:
arr

array([4, 5, 6, 2, 3, 7, 1, 0])

In [83]:
arr.byteswap()

array([ 67108864,  83886080, 100663296,  33554432,  50331648, 117440512,
        16777216,         0])

In [84]:
arr.byteswap(True)

array([ 67108864,  83886080, 100663296,  33554432,  50331648, 117440512,
        16777216,         0])

In [85]:
# copies and views

In [86]:
arr

array([ 67108864,  83886080, 100663296,  33554432,  50331648, 117440512,
        16777216,         0])

In [87]:
arr1

array([  0, 567,  34,  56,  89,   0,   0,  98])

In [89]:
a=np.copy(arr1)

In [90]:
a

array([  0, 567,  34,  56,  89,   0,   0,  98])

In [91]:
a[0]=4

In [92]:
a

array([  4, 567,  34,  56,  89,   0,   0,  98])

In [93]:
arr1

array([  0, 567,  34,  56,  89,   0,   0,  98])

In [99]:
## view is swallow copy and copy acts as deep copy

In [94]:
b=arr1.view()

In [95]:
b

array([  0, 567,  34,  56,  89,   0,   0,  98])

In [96]:
b[0]=9

In [97]:
b

array([  9, 567,  34,  56,  89,   0,   0,  98])

In [98]:
arr1

array([  9, 567,  34,  56,  89,   0,   0,  98])

In [101]:
# matrix library

In [102]:
import numpy.matlib as  nm

In [103]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [105]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [106]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [107]:
#linear algebra

In [108]:
arr

array([ 67108864,  83886080, 100663296,  33554432,  50331648, 117440512,
        16777216,         0])

In [115]:
arr1

array([  9, 567,  34,  56,  89,   0,   0,  98])

In [116]:
arr_1=np.random.randint([[2,3],[4,5]])
arr_2=np.random.randint([[5,3],[2,5]])

In [117]:
arr_2

array([[1, 0],
       [0, 1]])

In [118]:
arr_1

array([[0, 2],
       [2, 3]])

In [119]:
np.dot(arr_1,arr_2)

array([[0, 2],
       [2, 3]])

In [120]:
arr_1@arr_2

array([[0, 2],
       [2, 3]])