In [2]:
import numpy as np
list_ = [ 1 , 2 , 3,4 , 5 ]
array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [3]:
array_list

array([1, 2, 3, 4, 5])

In [5]:
list_

[1, 2, 3, 4, 5]

In [9]:
array_list.dtype

dtype('int32')

In [11]:
type(array_list)

numpy.ndarray

In [12]:
type(list_)

list

##  list_ is a Python list, while array_list is a numpy array, so their data types are different. We can use the type() function in Python to determine the data type of a variable.

# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [13]:
list_


[1, 2, 3, 4, 5]

In [14]:
array_list

array([1, 2, 3, 4, 5])

In [15]:
for element in array_list:
    print(type(element))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [16]:
for element in list_:
    print(type(element))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


# Q3. Considering the following changes in the variable, array_list:

In [17]:
array_list = np.array(object = list_, dtype = int)

In [18]:
array_list

array([1, 2, 3, 4, 5])

In [19]:
list_

[1, 2, 3, 4, 5]

In [20]:
type(array_list)

numpy.ndarray

In [21]:
type(list_)

list

In [22]:
for element in array_list:
    print(type(element))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [23]:
for element in list_:
    print(type(element))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


### Yes, there will be a difference in the data type of the elements present in the list_ and array_list variables, assuming that list_ contains elements of different data types and array_list is created with a specified data type. When creating array_list, we've specified a data type of int using the dtype argument. As a result, all elements in array_list will have the same data type of numpy.int64, regardless of their original data type in the list_ variable.

# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [24]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [26]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
## shape
np.shape(num_array)


(2, 3)

In [28]:
## size
np.size(num_array)

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [29]:
import numpy as np

In [32]:
arr_1=np.zeros((3,3))

In [33]:
arr_1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
arr_1.ndim

2

# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [39]:
arr_2=np.identity(5)

In [41]:
arr_2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])